version: '3.8'

services:
  repplus:
    build: .
    container_name: repplus
    restart: unless-stopped
    ports:
      - "127.0.0.1:3838:3838"
    environment:
      - SHINY_LOG_LEVEL=INFO
    mem_limit: 1g
    memswap_limit: 1g
    cpus: 1.0
    pids_limit: 200
